kind: Service
apiVersion: v1
metadata:
  name: hello-world
  labels:
    run: hello-world
spec:
  selector:
    run: hello-world
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 4000
  type: NodePort
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-world
  labels:
    run: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
        - name: hello-world
          image: sppatel/hello-world
          imagePullPolicy: Always
          ports:
            - containerPort: 4000